export const HANOI_WARDS = [
  "Phường Hoàn Kiếm",
  "Phường Cửa Nam",
  "Phường Ba Đình",
  "Phường Ngọc Hà",
  "Phường Giảng Võ",
  "Phường Hai Bà Trưng",
  "Phường Vĩnh Tuy",
  "Phường Bạch Mai",
  "Phường Đống Đa",
  "Phường Kim Liên",
  "Phường Văn Miếu - Quốc Tử Giám",
  "Phường Láng",
  "Phường Ô Chợ Dừa",
  "Phường Hồng Hà",
  "Phường Lĩnh Nam",
  "Phường Hoàng Mai",
  "Phường Vĩnh Hưng",
  "Phường Tương Mai",
  "Phường Định Công",
  "Phường Hoàng Liệt",
  "Phường Yên Sở",
  "Phường Thanh Xuân",
  "Phường Khương Đình",
  "Phường Phương Liệt",
  "Phường Cầu Giấy",
  "Phường Nghĩa Đô",
  "Phường Yên Hòa",
  "Phường Tây Hồ",
  "Phường Phú Thượng",
  "Phường Tây Tựu",
  "Phường Phú Diễn",
  "Phường Xuân Đỉnh",
  "Phường Đông Ngạc",
  "Phường Thượng Cát",
  "Phường Từ Liêm",
  "Phường Xuân Phương",
  "Phường Tây Mỗ",
  "Phường Đại Mỗ",
  "Phường Long Biên",
  "Phường Bồ Đề",
  "Phường Việt Hưng",
  "Phường Phúc Lợi",
  "Phường Hà Đông",
  "Phường Dương Nội",
  "Phường Yên Nghĩa",
  "Phường Phú Lương",
  "Phường Kiến Hưng",
  "Phường Thanh Liệt"
];
